version: "3"
services:
    react-app:
        container_name: rick-and-morty
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8082:80
        expose:
            - "8082"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
